export const imageSources = {
    "ARY News": "/images/news-sources/icons/ARY.png",
    "Ary News": "/images/news-sources/icons/ARY.png",
    "arynews.tv": "/images/news-sources/icons/ARY.png",
    'Dawn': "/images/news-sources/icons/dawn.png",
    "Dawn.com": "/images/news-sources/icons/dawn.png",
    "thenews.com.pk": "/images/news-sources/icons/TheNews.png",
    "The News": "/images/news-sources/icons/TheNews.png",
    "nation.com.pk": "/images/news-sources/icons/TheNation.png",
    "The Tribune": "/images/news-sources/icons/express_tribune.png",
    'Tribune': "/images/news-sources/icons/express_tribune.png",
    'Tribune.com.pk': "/images/news-sources/icons/express_tribune.png",
    'tribune.com.pk': "/images/news-sources/icons/express_tribune.png",
    "The Nation": "/images/news-sources/icons/TheNation.png",
    "Geo TV": "/images/news-sources/icons/Geo.png",
    "Geo News": "/images/news-sources/icons/Geo.png",
    "GEO News": "/images/news-sources/icons/Geo.png",
    "geo.tv": "/images/news-sources/icons/Geo.png",
    "GEO TV": "/images/news-sources/icons/Geo.png",
    "tribune.com.pk": "/images/news-sources/icons/express_tribune.png",
  };